### PR TITLE
Add contextual build status (e.g. FIXED, STILL FAILING) to title, some chores such as Jenkinsfile

### PR DESCRIPTION
**Pull request by justinharringa**
* Improved postRecovery help text
* Add Jenkinsfile in order to build on https://ci.jenkins.io

### CODE REVIEW

**Comment by justinharringa** [comment]
@superfell @sortiz-sfdc This should take care of the [first step of getting this on the Jenkins project's build servers at ci.jenkins.io](https://wiki.jenkins-ci.org/display/JENKINS/Hosting+Plugins#HostingPlugins-ci.jenkins.io) since I've added a Jenkinsfile with the buildPlugin() build step.

**Comment by justinharringa** [comment]
Next step seems to be:
> Adding plugin jobs to this Jenkins instance currently isn't automated (mainly for security reasons), so please open a new issue in [the INFRA project](https://issues.jenkins-ci.org/browse/INFRA), using the "ci" component, and with a title like "Add plugin build for snapchat-notification plugin". Make sure to add the GitHub URL of your Jenkinsfile in the issue description.

**Comment by justinharringa** [comment]
@superfell are you interested in help on the release process for this? I'd be happy to kick off the move to ci.jenkins.io and other release activities if you'd like. Don't want to step on toes, of course. 😄

**Comment by superfell** [comment]
Yes, would be happy to have some help, thanks!

**Pull request merged**
